jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: ./Lets-practice1

      - name: Build
        run: npm run build
        working-directory: ./Lets-practice1

      - name: Deploy
        run: |
          cp -r ./Lets-practice1/dist/* ./lets-practice/
          touch ./lets-practice/.nojekyll

